services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000' # APIエンドポイント
      - '9001:9001' # 管理用コンソール
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/data
    command: ['server', '/data', '--console-address', ':9001']

volumes:
  minio-data:
