version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
      - 6006:6006
    volumes:
      - ./frontend/app:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    tty: true
    stdin_open: true

volumes:
  frontend_node_modules: